In [2]:
import json
import pandas as pd

In [ ]:
with open("depo4.json", "r") as f:
    json_data = json.load(f)

# ambil khusus key "data"
df = pd.DataFrame(json_data["data_container"])
cols_check = ["cargo", "container_size", "grade", "no_container", "state", "tgl_status", "tier", "updated_at", "vvoy"]
mask = df[cols_check].apply(lambda row: all(val == "-" or val is None for val in row), axis=1)
filtered_df = df[~mask].copy()
filtered_df["container_size"] = filtered_df["container_size"].replace("-", "20 DC")

for col in ["column"]:
    filtered_df[col] = pd.to_numeric(filtered_df[col], errors="coerce")

df_40hc = filtered_df[filtered_df["container_size"] == "40 HC"].copy()
df_non_40hc = filtered_df[filtered_df["container_size"] != "40 HC"].copy()

df_40hc = (
    df_40hc.sort_values("column")
    .groupby("no_container", as_index=False)
    .first()
)

filtered_df = pd.concat([df_non_40hc, df_40hc], ignore_index=True)        
filtered_df["column"] = filtered_df["column"].astype(str)
print(filtered_df.dtypes)
print("dapat data", len(filtered_df))

import random
import string

# contoh fungsi untuk ubah no_container
def randomize_no_container(value):
    if value == "-":
        return value
    
    # generate 4 huruf random awal & akhir
    prefix = ''.join(random.choices(string.ascii_uppercase, k=4))
    suffix = ''.join(random.choices(string.ascii_uppercase, k=4))
    
    # ambil bagian tengah (tanpa 4 depan & 4 belakang)
    if len(value) > 8:
        middle = value[4:-4]
    else:
        middle = ""
    
    return prefix + middle + suffix


df["no_container_new"] = df["no_container"].apply(randomize_no_container)

block             object
cargo             object
column            object
container_size    object
depo              object
grade             object
no_container      object
row               object
state             object
tgl_status        object
tier              object
updated_at        object
vvoy              object
dtype: object
dapat data 1228

In [7]:
filtered_df

,block,cargo,column,container_size,depo,grade,no_container,row,state,tgl_status,tier,updated_at,vvoy
0,E,-,1,20 DC,DEPO 4,-,-,1,-,-,1,-,-
1,A,-,1,20 DC,DEPO 4,-,-,1,-,-,1,-,-
2,D,-,1,20 DC,DEPO 4,-,-,1,-,-,1,-,-
3,G,-,1,20 DC,DEPO 4,-,-,1,-,-,1,-,-
4,F1,-,1,20 DC,DEPO 4,-,-,1,-,-,1,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1223,F,PLASTIK,14,40 HC,DEPO 4,C,SPNU4613850,1,MTB,30-09-2025,2,30-09-2025 14:10:54,PAH-32/2025 SBY-GTO
1224,G,MAKANAN,1,40 HC,DEPO 4,A,SPNU4618450,1,FTL,01-10-2025,4,01-10-2025 17:05:09,TFL-26/2025 SBY-BAU
1225,J,KONTAINER KOSONG (COC),7,40 HC,DEPO 4,A,SPNU4618609,5,MTS,02-10-2025,5,02-10-2025 07:51:37,HAY-10/2025 MKE-SBY
1226,J,KONTAINER KOSONG (COC),8,40 HC,DEPO 4,B,SPNU4620674,2,MTS,02-10-2025,2,02-10-2025 07:52:11,HJE-12/2025 PAL-SBY
1227,J,KONTAINER KOSONG (COC),8,40 HC,DEPO 4,A,SPNU4630158,3,MTS,02-10-2025,3,02-10-2025 07:52:36,HJE-12/2025 BPN-SBY